### ISSUE TITLE
Update repository according to current SDK

### ISSUE THREAD

**Issue by Bertuzb** [appcelerator/titanium#240]
For some reason, `titanium sdk install` has fewer options than `appc ti sdk install`. They should both offer the same releases. Why are these 2 derailed?

**Comment by cb1kenobi** [comment]
It's because we no longer offer stable, supported Titanium SDK releases to open source users. If you want to use just the Titanium CLI, then you must build a Titanium SDK from source. If you want stable, supported Titanium SDK releases, then you have to use the Appc CLI so that it can verify who you are and what you are entitled to.

**Comment by Bertuzb** [comment]
so this npm package is just going to die out? what about alloy npm package? I see a huge opportunity in where coders could just install the npm modules and their dependencies manually. Can I conclude that Appcelerator is moving towards closed source?

**Comment by cb1kenobi** [comment]
Not quite. The Appc CLI is actually a wrapper around the Titanium CLI. It modifies the behavior of the Titanium CLI by enforcing entitlements and such.

As for Alloy, the Alloy npm module is going to die because it Alloy is going to move directly into the Titanium SDK! This is good for a number of reasons: aligned with Titanium SDK features, faster builds, support for ES2015 (ES6), and much more. And yes, Alloy and the Titanium SDK will continue to be open source. :)
