### ISSUE TITLE
Can only install SDK up to version 4.0.0.GA

### ISSUE THREAD

**Issue by Bostwickenator** [appcelerator/titanium#243]
Am I missing something here or can you only install SDK up to version 4.0.0.GA. If so there should be a note in the readme of this project (such that it is displayed on the git hub page) noting that the appcelerator SDKs including the titanium ones should now be installed via the https://www.npmjs.com/package/appcelerator package. Even better put this note in the help when you run this CLI's sdk function.

**Comment by cb1kenobi** [comment]
It's a little complicated. The available Titanium SDK releases depends on if you're using `ti sdk` vs `appc ti sdk`. `appc ti sdk` shows the latest and greatest SDKs. `ti sdk` shows the latest release before the switch from the Titanium CLI to the Appcelerator CLI.

The list of releases for the Titanium CLI is no longer automatically updated, but rather it's a manual process. Because we haven't determined which past releases should be available to `ti sdk`, we simply haven't updated the release list.

However, the list of releases that `appc ti sdk` reference is automatically updated and current, so I advise you just use `appc ti sdk` for now.

**Comment by Bostwickenator** [comment]
That's exactly my point I should use appc. However nothing here notes this to people who are used to using the ti cli. You should inform them that the appc package may have a more complete list of SDKs.

**Comment by av-k** [comment]
Maybe helful,
`appc ti sdk install 6.1.2.GA --force`
where **6.1.2** your version.
