### ISSUE TITLE
Relaunch app instead of simulator

### ISSUE THREAD

**Issue by sindresorhus** [appcelerator/titanium#56]
The module [titanium-refresh](https://github.com/frontseat2/titanium-refresh) does this. Would be useful if the official tool could do that same.

**Comment by caspahouzer** [comment]
try http://tishadow.yydigital.com

**Comment by skypanther** [comment]
Given that this issue is well over a year old, I'm going to close it. As @caspahouzer points out TiShadow or Appcelerator's LiveView offer greater optimizations than just keeping the simulator open. Feel free to open an [improvement Jira ticket](https://jira.appcelerator.org) if you still feel we should add this feature.
